### ISSUE TITLE
Missing parameter documentation

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#22]
Thanks for adding these default values, however, I am still missing the description of these parameters. What do they actually control? Thanks for completing the documentation with the descriptions!

_Originally posted by @tp-development in https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/issues/20#issuecomment-1500416736_

**Comment by tp-development** [comment]
Thanks for adding these default values, however, I am still missing the description of these parameters. What do they actually control? Thanks for completing the documentation with the descriptions!

**Comment by GBonnaire** [comment]
Hi,

You can found more informations on the parameters here : https://thisancog.github.io/statistics.js/

It's this library used by my plugins. I will complete my documentation with all descriptions (from this site) of each formula

**Comment by GBonnaire** [comment]
Which parameters do you want more description?

**Comment by tp-development** [comment]
Generally wherever the following parameters are used: (multiple formulas)
- scale, scaleOfFirstColumn, scaleOfSecondColumn
- epsilon
- spougeConstant

I didn't find information on what they control and what are their possible values.

**Comment by GBonnaire** [comment]
### [Scales of measure](https://thisancog.github.io/statistics.js/index.html#scalesofmeasure)

[More info](https://en.wikipedia.org/wiki/Level_of_measurement)
Statistical variables are usually distinguished by there scale of measure. A scale of measure describes the nature of the data assigned to a variable and thus permits (and forbids) how the variable can be manipulated and treated by statistical methods. It is highly encouraged to declare the scale of measure for each variable, as statistics.js will prevent any methods that are not valid for a given variable based on its scale of measurement. ([see above](https://thisancog.github.io/statistics.js/index.html#enteringdata) on how to define a variable’s scale of measure)

According to Stanley Smith Stevens’ typology, scales of measure can be ordered by their level of sophisticiation where a given scale inherits all the valid methods from its precursor and adds new features:
`nominal scale`: This scale allows for classification only. The possible values are all distinct and mutually exclusive, can not be ordered or quantified. Therefore, values allow only for equality, not for comparison, can not be summed, substracted, multiplied or divided. The [mode](https://thisancog.github.io/statistics.js/inc/measures.html#median) – the most common value – can be computed. A nominal variable that has only two values is also called dichotomous. Examples: gender, nationality, genre.
`ordinal scale`: This scale introduces order in the form of ranks but does not account for the amount of difference between two given values. Values can be compared and sorted, but not summed, substracted, multiplied or divided. The [median](https://thisancog.github.io/statistics.js/inc/measures.html#median) – the middle rank – can be computed. Some dichotomous variables can be on the ordinal scale if there is a sense of order, such as "guilty"/ "not guilty". Non-dichotomous examples include the Likert scale for measuring the level of agreement ("disagree", "somewhat disagree", "neutral", "somewhat agree", "agree") or school grades (where technically the difference between two values is not defined but often the [arithmetic mean](https://thisancog.github.io/statistics.js/inc/measures.html#arithmeticmean) is calculated anyway).
`interval scale`: This scale extends the ordinal scale by defining the amount of difference between two given values, e.g. the base metric upon which the space of all valid values is constructed. It introduces addition and subtraction, but does not allow for multiplication nor division as it lacks a meaningful, natural zero. For example, on the Celsius temperature scale, it is not meaningful to say that 30°C is twice as hot as 15°C. On the interval scale, the [arithmetic mean](https://thisancog.github.io/statistics.js/inc/measures.html#arithmeticmean) and the [standard deviation](https://thisancog.github.io/statistics.js/inc/measures.html#standarddeviation) can be determined. Examples: temperature on the Celsius scale (0°C is an arbitrary zero, whereas 0°K is a natural zero), percentage, location in space.
`metric scale`: This scale extends the interval scale by defining a meaningful zero and therefore permits multiplication and division. The [geometric](https://thisancog.github.io/statistics.js/inc/measures.html#geometricmean) and the [harmonic mean](https://thisancog.github.io/statistics.js/inc/measures.html#harmonicmean) are introduced on this scale. Examples: mass, length, concentration of a chemical compound.

### [Settings](https://thisancog.github.io/statistics.js/index.html#settings)

There are several settings you can adjust in order to change the behaviour of the library. You can pass one or several of them as an object upon initialisation.
`epsilon` (default: 0.00001): The calculation of some statistical methods would progress forever, however for computational means a stopping variable epsilon is introduced. It’s value is used as the boundary until where a iterative method will be executed. Generally, smaller values give more precision and result in longer computation times.
excludeColumns (default: ["ID", "id"]): Accepts an array of strings that are names of the columns to ignore when assigning a scale of measure.
`spougeConstant` (default: 40): Defines the constant a in Spouge’s approximation of the [gamma function](https://thisancog.github.io/statistics.js/inc/algebra.html#gamma).


With this extract, do you have all answers ?

**Comment by tp-development** [comment]
Yes, thanks for elaborating on this - I am good! Would you plan to include this information in the package documentation for other users that might have similar questions?

**Comment by GBonnaire** [comment]
Yes, it's include on documentation. 

Have a good day
