### ISSUE TITLE
documentation link on the formula-plugin page is broken

### ISSUE THREAD

**Issue by pwiegers** [GBonnaire/jspreadsheet-plugins-and-editors#6]
Hi Guillaume,

the link on the page: https://repo.gbonnaire.fr/product/jss-plugin-formula to the github doc is broken.
I just bought it, expecting the doc also to be included in the package. This appears not to be the case. 
I think I found the correct documentation here: https://github.com/jspreadsheet/plugins/tree/master/formula
but this is obviously not optimal :-)

Also, I feel I miss some important point with the versions. If I inlcude the formula code, it will complain about missing modules:
  "jspreadsheet-pro" in /home/paul/Documents/dev/M323/client/compatibility/13_jss.formula.js (web.browser.legacy)
  "formula-pro" in /home/paul/Documents/dev/M323/client/compatibility/13_jss.formula.js (web.browser.legacy)
and it does not work correctly. It shows the forumla-bar, but the functionality is broken. (Random newlines, strange glitching of the cursor.)
So, obviously, I'm doing something wrong with the verion of jspreadsheet? I just downloaded the version from here:
https://jspreadsheet.com/v8/docs/getting-started
and included the licence-key. Is there a "pro"-version somewhere else?

regards,

Paul

**Comment by GBonnaire** [comment]
Hi,

Documentation is here on github / wiki
link : https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/wiki/Premium-plugin-:-Formula

You need extention formula-pro of jSpreadsheet : https://jspreadsheet.com/products/formulas

And for break line/cursor, i will fixe that

thank you

regards,

**Comment by pwiegers** [comment]
Hi Guillaume,

your response time is amazing!
I found the doc on my own, as I said; but you could update the link that points to the wrong github page.

As to the plugins/spreadsheet, this is  a bit messy.
There are several versions of the spreadsheet called "pro" and apparently several versions of the formula plugin.
If I go to the page you point me to:
https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/wiki/Premium-plugin-:-Formula
it states that I need to go here:
https://repo.gbonnaire.fr/
to purchse a licence. I did that, for 100,- a year - which I paid this morning.
Now, you tell me to go here:
https://jspreadsheet.com/products/formulas
and pay 360 pounds - one time licence.

I don't mind paying for this piece of software, neither for the spreadsheet itself, but this is a) confusing, b) anoying (if I pay for something I want to know for sure I buy the right version!) and c) unprofessional.

So, can you please:
1) confirm that if I buy from https://jspreadsheet.com/products/formulas it will work (it has no demo page, but that is the same plugin as from your site?)
2) I need the formula-plugin for multiple domains, just like the spreadsheet. Can you please advise?
2) cancel and refund my subscription I bought from your website

As a side note, I would like to know your involvement in all of this. Is jSpreadsheet your product? Are you affiliated with the company? 
The reason I'm asking is dat I need the spreadsheet to be, well, predictable and stable. As I am planning to incorporate this into my own app, I want to be more sure about this product. As I described above, this feels a bit, well, messy...

I do not want to be overly critical, as I am impressed by the product, but even great products need clarity and support :-)

regards,

Paul

**Comment by GBonnaire** [comment]
I try to answer to each question :

- The link of documentation was updated this morning after your message 😉 

- No, you need extension of jspreadsheet call "formula-pro", but in this extension you have 2 versions, 1 basic (free) and 1 pro (to purchase, with more formulas)
link to basic JS : `https://jspreadsheet.com/v8/plugins/formula.js`
link to pro Js : `https://jspreadsheet.com/v8/plugins/formula-pro.js`
This extension is writed by editor of jspreadsheet pro (Paul Hodel)

- My plugin formula ( is an editor formulabar and an editor formula in cell) is an plugin for jspreadsheet pro to add documentation + input bar when you want write formula. If you want only formula calculation : you need only add extensions "formula-pro" of jspreadsheet with basic link or pro link; For help you can request here : https://github.com/jspreadsheet/pro/issues
- I am an independant editor and jspreadsheet pro is not my own product, it is a product of Paul Hodel compagny (https://github.com/pphod or https://github.com/hodeware). But, i suggest to Paul the ideas to improve jspreadsheet and help sometime to improve jspreadsheet, because i'm also an user of jspreadsheet pro for my own application (www.osilap.fr)

Ok i cancel your subscription.

I understand your notice, and i think to improve information linked about my plugins for more clear informations. Thank you for that.

regards,

guillaume

**Comment by pwiegers** [comment]
Hi Guillaume,

thank you for your answers!
So, to use the formula-bar I need the pro version of the spreadsheet, and the (free or not) plugin formula-pro?
In that case, keep my subscription alive! :-D
I will try to implement this in my app.

Checked out your website; Je ne parle pa francais... dommage :-)

regards,

Paul

**Comment by GBonnaire** [comment]
Yes : for plugin formula plugin (renamed by Formula Editors advanced) you required : 
- JSpreadsheet pro version V7 or V8
- Extension formula (basic or pro) of jspreadsheet
- And my plugin

Oups, your subscription  for this year is refunded and i can't cancel this request... But your subscript keep alive (with renewal year)

but it's ok, it's christmas and considere this as a gift for you 😉,  i keep activate your license for 1 year of subscription and i would like you continue your contribution to improve my documentation, information and bugs 😉 

Are you ok with this deal ?

lol yes, i'm french and based on France 😁 And my own application is for Publics administrations(FR) and hospitals(FR)

happy new year's eve

regards,

Guillaume

**Comment by pwiegers** [comment]
Hi Guillaume,

that is amazing! I'm signing off for to day; will try to incorporate all in my app tomorrow :-)

Bon Annee to you!

regards,

Paul

**Comment by GBonnaire** [comment]
Happy new year to you 😊 

regards
